### PR TITLE
Explain MapFactory

### PR DESCRIPTION
**Pull request by Nakaner**

### CODE REVIEW

**Comment by joto** [comment]
This is only half of it, the "dynamic" way of choosing an index. The static way is not described here, but is part of the description in `visitors-and-handlers.md`. That is confusing. Can you move the stuff over from there and explain when to use one or the other?

**Comment by Nakaner** [comment]
I wanted to show a runnable example of a handler using a LocationHandler and decided to keep the example in the handler section simple and stupid. What do you think about explaining the static way here and keeping the stupid example in the Handler section as it is. The alternative is that we drop the Indexes section of the libosmium-manual at all and integrate its content into the Handlers section.

**Comment by joto** [comment]
We can't drop the section, indexes need to be explained by themselves. The example in the Handler section can stay there, because it is also explaining how to use the Handler, but the details should be in the Index section.

**Comment by joto** [comment]
The manual moved to the website repository. I have added the content of this pull request there.

**Pull request closed without merging**
